version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10
workflows:
  version: 2

  ci:
    jobs:
      - install
      - test:
          requires:
            - install

jobs:
  install:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace: 
        root: .
        path:
          - node_modules
  test:
    executor: node
    steps:
      - attach_workspace:
        root: .
      - run: yarn test
